### ISSUE TITLE
我也用花儿五笔，也会小鹤双拼。但不会Python，请问怎么用？

### ISSUE THREAD

**Issue by houinchengdu** [Snoire/ulpb#1]
请问怎么用？我装有Python。

**Comment by Snoire** [comment]
可以直接在 https://github.com/Snoire/ulpb/releases 里下载我处理好的码表（ulpb.txt）。把花儿五笔的拼音码表删掉，再导入这个就可以用了。或者不删除直接导入，这样全拼和双拼应该会共存。

如果你想自己处理，需要先下载 pypinyin 库：
pip install pypinyin
然后再执行命令：
python ulpb2.py <全拼码表.txt> <双拼码表.txt>
<全拼码表.txt> 是从花儿五笔导出的拼音码表，<双拼码表.txt> 是生成的文件。

**Comment by houinchengdu** [comment]
处理成功了！谢谢！！
